// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetChat.Persistence;

namespace NetChat.Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20211106160435_SendData")]
    partial class SendData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.11");

            modelBuilder.Entity("NetChat.Domain.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Channels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8deb6cd6-71f8-4871-a56c-a666c93ad6bb"),
                            Description = "Dedicated channel to NetCore",
                            Name = "DotNetCore"
                        },
                        new
                        {
                            Id = new Guid("ba6a0cb2-34d3-42fa-beb2-b38acd8e22b6"),
                            Description = "Dedicated channel to ReacJS",
                            Name = "Reac JS"
                        },
                        new
                        {
                            Id = new Guid("dc924665-25e4-42bb-8144-14976986e74b"),
                            Description = "Dedicated channel to Angular",
                            Name = "Angular"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
